Adding timer format
Crystalwarrior/KFO-Client pull request #13
Opened 2024-05-14 14:06 UTC by EstatoDeviato

2024-05-14 23:06 UTC, Crystalwarrior requested changes
Good stuff, just parse the arguments in packet_distribution rather than courtroom

2024-05-14 23:06 UTC, Crystalwarrior commented on src/courtroom.cpp
> +void Courtroom::format_clock(QStringList time_format) {
Why is this function responsible for parsing the arguments? Pass the arguments here and handle the QStringList unpacking in packet_distribution.cpp

2024-05-14 23:06 UTC, Crystalwarrior commented on src/packet_distribution.cpp
> +      QStringList time_format = f_contents;
Break this up into arguments and pass it to format_clock instead of doing it in format_clock

2024-05-18 12:47 UTC, EstatoDeviato commented
Done!
Now it is unpacked in packet_distribution file

2024-05-26 20:10 UTC, merged